import { db } from "@/lib/db"

export const GLOSSARY_TERMS = [
  {
    term: "SEO",
    slug: "seo",
    definition: "Conjunto de tecnicas para fazer seu site aparecer nos primeiros resultados do Google sem pagar por anuncios.",
    analogy: "Eh como organizar sua vitrine para que as pessoas que passam na rua encontrem exatamente o que procuram.",
    category: "SEO",
    relatedTerms: ["palavra-chave", "serp", "trafego-organico"],
  },
  {
    term: "Palavra-chave",
    slug: "palavra-chave",
    definition: "Termo ou frase que as pessoas digitam no Google quando estao procurando algo.",
    analogy: "Eh como a pergunta que o cliente faz quando entra na sua loja: 'Voce tem sapato preto numero 40?'",
    category: "SEO",
    relatedTerms: ["seo", "serp", "cpc"],
  },
  {
    term: "SERP",
    slug: "serp",
    definition: "Pagina de resultados do Google. Eh o que aparece quando voce faz uma busca.",
    analogy: "Eh como o mural de classificados onde todos os negocios competem por atencao.",
    category: "SEO",
    relatedTerms: ["seo", "palavra-chave", "trafego-organico"],
  },
  {
    term: "Backlink",
    slug: "backlink",
    definition: "Link de outro site que aponta para o seu. Quanto mais sites confiáveis linkarem para voce, melhor seu SEO.",
    analogy: "Eh como uma recomendacao boca a boca: quando alguem de confianca indica seu negocio, mais pessoas confiam em voce.",
    category: "SEO",
    relatedTerms: ["link-building", "autoridade-de-dominio", "seo"],
  },
  {
    term: "Meta Description",
    slug: "meta-description",
    definition: "Texto curto que aparece embaixo do titulo do seu site nos resultados do Google.",
    analogy: "Eh como o resumo na contracapa de um livro que te convence a abrir e ler.",
    category: "SEO",
    relatedTerms: ["title-tag", "serp", "seo"],
  },
  {
    term: "Title Tag",
    slug: "title-tag",
    definition: "Titulo da sua pagina que aparece nos resultados do Google e na aba do navegador.",
    analogy: "Eh como a placa na frente da sua loja — precisa ser clara e atrativa.",
    category: "SEO",
    relatedTerms: ["meta-description", "seo", "serp"],
  },
  {
    term: "Sitemap",
    slug: "sitemap",
    definition: "Arquivo que lista todas as paginas do seu site para o Google encontrar.",
    analogy: "Eh como o indice de um livro que mostra onde cada capitulo esta.",
    category: "SEO",
    relatedTerms: ["robots-txt", "indexacao", "seo"],
  },
  {
    term: "Robots.txt",
    slug: "robots-txt",
    definition: "Arquivo que diz ao Google quais paginas do seu site ele pode ou nao visitar.",
    analogy: "Eh como uma placa de 'permitido' ou 'proibido' na entrada de cada sala do seu negocio.",
    category: "SEO",
    relatedTerms: ["sitemap", "indexacao", "seo"],
  },
  {
    term: "Link Building",
    slug: "link-building",
    definition: "Estrategia de conseguir que outros sites coloquem links apontando para o seu.",
    analogy: "Eh como fazer parcerias com outros negocios para que eles indiquem clientes para voce.",
    category: "SEO",
    relatedTerms: ["backlink", "autoridade-de-dominio", "seo"],
  },
  {
    term: "Autoridade de Dominio",
    slug: "autoridade-de-dominio",
    definition: "Pontuacao que mede o quao confiavel e relevante o Google considera seu site.",
    analogy: "Eh como a reputacao de um restaurante — quanto mais estrelas e avaliacoes positivas, mais clientes confiam.",
    category: "SEO",
    relatedTerms: ["backlink", "link-building", "seo"],
  },
  {
    term: "Trafego Organico",
    slug: "trafego-organico",
    definition: "Visitantes que chegam ao seu site atraves dos resultados gratuitos do Google.",
    analogy: "Eh como os clientes que entram na sua loja porque passaram na frente e gostaram da vitrine, sem voce pagar por propaganda.",
    category: "SEO",
    relatedTerms: ["seo", "trafego-pago", "serp"],
  },
  {
    term: "Indexacao",
    slug: "indexacao",
    definition: "Processo pelo qual o Google descobre e registra as paginas do seu site no seu banco de dados.",
    analogy: "Eh como quando uma biblioteca cataloga um livro novo para que as pessoas possam encontra-lo.",
    category: "SEO",
    relatedTerms: ["sitemap", "robots-txt", "seo"],
  },
  {
    term: "CPC",
    slug: "cpc",
    definition: "Custo Por Clique — quanto voce paga cada vez que alguem clica no seu anuncio.",
    analogy: "Eh como pagar um panfleteiro so quando alguem realmente pega o panfleto e entra na loja.",
    category: "Anuncios",
    relatedTerms: ["cpm", "ctr", "trafego-pago"],
  },
  {
    term: "CPM",
    slug: "cpm",
    definition: "Custo Por Mil Impressoes — quanto voce paga a cada mil vezes que seu anuncio aparece.",
    analogy: "Eh como pagar pelo outdoor na avenida movimentada: voce paga pela exposicao, nao pelos clientes que entram.",
    category: "Anuncios",
    relatedTerms: ["cpc", "impressoes", "trafego-pago"],
  },
  {
    term: "CTR",
    slug: "ctr",
    definition: "Taxa de Cliques — porcentagem de pessoas que viram seu anuncio ou resultado e clicaram nele.",
    analogy: "Se 100 pessoas passam pela sua loja e 5 entram, seu CTR eh 5%.",
    category: "Anuncios",
    relatedTerms: ["cpc", "impressoes", "conversao"],
  },
  {
    term: "CPA",
    slug: "cpa",
    definition: "Custo Por Aquisicao — quanto voce gasta em marketing para conseguir um novo cliente.",
    analogy: "Se voce gastou R$100 em propaganda e ganhou 2 clientes, seu CPA eh R$50.",
    category: "Anuncios",
    relatedTerms: ["roas", "roi", "conversao"],
  },
  {
    term: "ROAS",
    slug: "roas",
    definition: "Retorno Sobre o Gasto com Anuncios — quanto voce ganha para cada real investido em anuncios.",
    analogy: "Se voce investiu R$100 e vendeu R$500, seu ROAS eh 5x — cada real investido voltou como cinco.",
    category: "Anuncios",
    relatedTerms: ["roi", "cpa", "trafego-pago"],
  },
  {
    term: "Trafego Pago",
    slug: "trafego-pago",
    definition: "Visitantes que chegam ao seu site porque voce pagou por anuncios no Google, Facebook, Instagram etc.",
    analogy: "Eh como contratar um promotor para distribuir panfletos e trazer pessoas para sua loja.",
    category: "Anuncios",
    relatedTerms: ["trafego-organico", "cpc", "roas"],
  },
  {
    term: "Remarketing",
    slug: "remarketing",
    definition: "Tecnica de mostrar anuncios para pessoas que ja visitaram seu site antes.",
    analogy: "Eh como quando voce olha um produto na vitrine e depois ve propagandas dele em todo lugar te lembrando de voltar.",
    category: "Anuncios",
    relatedTerms: ["pixel", "publico-alvo", "conversao"],
  },
  {
    term: "Publico-alvo",
    slug: "publico-alvo",
    definition: "Grupo de pessoas com maior chance de comprar seu produto ou servico.",
    analogy: "Se voce vende racao para gatos, seu publico-alvo sao donos de gatos — nao adianta anunciar para quem tem peixe.",
    category: "Anuncios",
    relatedTerms: ["remarketing", "pixel", "landing-page"],
  },
  {
    term: "Pixel",
    slug: "pixel",
    definition: "Codigo invisivel no seu site que rastreia o que os visitantes fazem, usado para medir resultados de anuncios.",
    analogy: "Eh como uma camera de seguranca discreta que registra quantas pessoas entraram, o que olharam e o que compraram.",
    category: "Anuncios",
    relatedTerms: ["remarketing", "conversao", "publico-alvo"],
  },
  {
    term: "Landing Page",
    slug: "landing-page",
    definition: "Pagina especial criada para convencer o visitante a fazer uma acao, como comprar ou se cadastrar.",
    analogy: "Eh como um vendedor focado que recebe o cliente na porta e o guia direto ate o produto certo.",
    category: "Geral",
    relatedTerms: ["conversao", "ctr", "teste-ab"],
  },
  {
    term: "Conversao",
    slug: "conversao",
    definition: "Quando um visitante faz a acao que voce queria — comprar, se cadastrar, baixar algo.",
    analogy: "Eh o momento em que a pessoa que estava 'so olhando' decide comprar.",
    category: "Geral",
    relatedTerms: ["landing-page", "funil-de-vendas", "cpa"],
  },
  {
    term: "Funil de Vendas",
    slug: "funil-de-vendas",
    definition: "Caminho que o cliente percorre desde conhecer seu negocio ate comprar: atracao, interesse, decisao e acao.",
    analogy: "Eh como um funil de cozinha: muita gente entra no topo (conhece voce) mas so algumas saem embaixo (compram).",
    category: "Geral",
    relatedTerms: ["conversao", "landing-page", "publico-alvo"],
  },
  {
    term: "Teste A/B",
    slug: "teste-ab",
    definition: "Comparar duas versoes de uma pagina ou anuncio para ver qual funciona melhor.",
    analogy: "Eh como testar duas receitas de bolo com clientes diferentes para descobrir qual vende mais.",
    category: "Geral",
    relatedTerms: ["landing-page", "conversao", "ctr"],
  },
  {
    term: "Impressoes",
    slug: "impressoes",
    definition: "Numero de vezes que seu anuncio ou conteudo apareceu na tela de alguem.",
    analogy: "Eh como contar quantas pessoas passaram e viram seu cartaz, mesmo que nao tenham parado para ler.",
    category: "Analytics",
    relatedTerms: ["cpm", "ctr", "alcance"],
  },
  {
    term: "Google Analytics",
    slug: "google-analytics",
    definition: "Ferramenta gratuita do Google que mostra quantas pessoas visitam seu site, de onde vem e o que fazem.",
    analogy: "Eh como ter um relatorio completo de movimento da loja: quantos entraram, quanto tempo ficaram e o que compraram.",
    category: "Analytics",
    relatedTerms: ["sessao", "taxa-de-rejeicao", "conversao"],
  },
  {
    term: "Taxa de Rejeicao",
    slug: "taxa-de-rejeicao",
    definition: "Porcentagem de pessoas que entram no seu site e saem sem clicar em nada.",
    analogy: "Eh como a pessoa que abre a porta da loja, da uma olhada e sai sem falar com ninguem.",
    category: "Analytics",
    relatedTerms: ["sessao", "google-analytics", "landing-page"],
  },
  {
    term: "Sessao",
    slug: "sessao",
    definition: "Uma visita ao seu site. Se a mesma pessoa voltar depois, conta como outra sessao.",
    analogy: "Eh como cada vez que um cliente entra na loja — se ele sai e volta a tarde, sao duas visitas.",
    category: "Analytics",
    relatedTerms: ["google-analytics", "taxa-de-rejeicao", "impressoes"],
  },
  {
    term: "ROI",
    slug: "roi",
    definition: "Retorno Sobre Investimento — quanto lucro voce teve em relacao ao que investiu.",
    analogy: "Se voce investiu R$100 e ganhou R$300, seu ROI eh 200% — voce triplicou seu dinheiro.",
    category: "Analytics",
    relatedTerms: ["roas", "cpa", "conversao"],
  },
  {
    term: "Engajamento",
    slug: "engajamento",
    definition: "Nivel de interacao do publico com seu conteudo: curtidas, comentarios, compartilhamentos e cliques.",
    analogy: "Eh como a diferenca entre alguem que so passa pela vitrine e alguem que entra, experimenta e recomenda para amigos.",
    category: "Social Media",
    relatedTerms: ["alcance", "hashtag", "impressoes"],
  },
  {
    term: "Alcance",
    slug: "alcance",
    definition: "Numero de pessoas unicas que viram seu conteudo ou anuncio.",
    analogy: "Se 500 pessoas diferentes viram seu post, seu alcance eh 500 — mesmo que algumas tenham visto mais de uma vez.",
    category: "Social Media",
    relatedTerms: ["impressoes", "engajamento", "hashtag"],
  },
  {
    term: "Hashtag",
    slug: "hashtag",
    definition: "Palavra ou frase precedida de # usada para categorizar conteudos nas redes sociais.",
    analogy: "Eh como colocar etiquetas nos produtos da loja para que os clientes encontrem por categoria.",
    category: "Social Media",
    relatedTerms: ["engajamento", "alcance"],
  },
]

export async function seedGlossary() {
  for (const term of GLOSSARY_TERMS) {
    await db.glossaryTerm.upsert({
      where: { slug: term.slug },
      update: {
        term: term.term,
        definition: term.definition,
        analogy: term.analogy,
        category: term.category,
        relatedTerms: term.relatedTerms,
      },
      create: {
        term: term.term,
        slug: term.slug,
        definition: term.definition,
        analogy: term.analogy,
        category: term.category,
        relatedTerms: term.relatedTerms,
      },
    })
  }
}
